version: '3.10'

services:
  tokenizer-flask-api:
    image: tokenizer-flask-api:latest
    environment:
      REDIS_URL: "redis"
    build:
      context:  Services/Tokenizer/tokenizer-flask-api
      dockerfile: Dockerfile
    ports: 
    - 5000:8080
  react-web:
    image: jpreader-react:latest
    build:
      context: Web/WebReact
      dockerfile: Dockerfile
    ports: 
    - 8080:80
  redis:
    image: redis:7.0.4
    ports: 
      - 6379:6379
